### PR TITLE
(#89,#90) Autosuggest & Search Results Character Limit

### LINKED ISSUE #70: Search result is not returned for some terms with Contains search
### Issue description
*Description of the issue*
On performing search using "len" and then selecting "anti-CD22 scFv TCRz:41BB-CAR lentiviral vector-transduced autologous T lymphocytes" from the autosuggest using a contains search on react-dev, when we select and submit this term, we do not get any search result. 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Select the "Contains" radio button on https://react-app-dev.cancer.gov/drug-dictionary-app/pr-68 
2. Type "len" and then select the term "anti-CD22 scFv TCRz:41BB-CAR lentiviral vector-transduced autologous T lymphocytes" from the autosuggest drop-down
3. Click the Search button.
4. No search result is returned.

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot

image

### Related Tickets
* Issue #9999
* Issue #9999

### LINKED ISSUE #89: Search Results for more than 30 characters
### Issue description
Having more than 30 characters when submitting a contains search is causing issues with our backend, and with search functionality in that even having a term with more than 30 characters leads the user to the "no results found page" even though there might be matching results .  We would like the limit the user to 30 characters only

> **ESTIMATE** TBD

### What's the expected change?
Users are only allowed to enter 30 characters in the search box, and there is helper text below the input field that says "Please enter up to 30 characters for your search"

### What's the current functionality?
Right now, the system breaks for contains searches more than 30 characters

### What's the updated acceptance criteria?
```gherkin
Scenario: User attempts search with more than 30 characters
Given that the user is doing a contains search in the search box within the drug dictionary
  Then the user is limited to only 30 characters in the search box
  And the system displays a message below the input box that says "Please enter up to 30 characters for your search."
  When user clicks search
  Then search returns results matching the first 30 characters entered
```

```gherkin
Scenario: User enters more than 30, then deletes characters to be less than 30
Given that the user is doing a search in the search box within the drug dictionary
  And the user attempts to type more than 30 characters in the search box
  Then the system does not allow users to enter more than 30 characters (the field is limited)
    When user clicks search
    Then the system executes the search on the 30 characters entered
```

### Additional details / screenshot
Styles: Noto Sans Regular 14px #2e2e2e line height: 16px
Padding: 30px above, 20px below

### Related Tickets
* CR #90

### LINKED ISSUE #90: Change Autosuggest to stop appearing after 30 characters
### Issue description
Currently, autosuggest will continue to display its suggested options in the dropdown regardless of how many characters a user types.  We would like autosuggest to stop displaying after the user has entered more than 30 characters.  In a separate ticket, we will address what should happen to search if a user enters more than 30 characters (#89)

> **ESTIMATE** TBD

### What's the expected change?
Users are no longer allowed to enter more than 30 characters in the field, and we stop displaying matching autosuggest terms, and instead, display a warning message on the input field "Please enter up to 30 characters for your search.".  Separately in the API, we will limit autosuggest to only return results under 30 characters

### What's the current functionality?
Currently, users can enter as many characters as they want and autosuggest will continue to match

### What's the updated acceptance criteria?
```gherkin
Scenario: User tries to type more than 30 characters 
Given user is typing in the search box for a starts with search
  When the user types more than 30 characters, the user is not able to enter anymore characters
```
```gherkin
Scenario: User tries to copy in more than 30 characters to the search box
Given user is tries to copy paste more than 30 characters into the search box 
  Then the system truncates the copied text to 30 characters
```

```gherkin
Scenario: Autosuggest appears after between 3 and 30 characters
Given user is typing in the search box for a contains or starts with search
  When the user types more than 3 characters
     And less than 30 characters
     Then autosuggest shows matches to the user's entered text and does not display the warning message
```

### Additional details / screenshot
- Screenshot

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #89
Closes #90
Closes #70 

(#89) search for over 30 characters

* Limited search to 30 chars for contains
* Added integration tests

(#90) Change Autosuggest to stop appearing after 30 characters

* Stop autosuggest options from being displayed after 30 characters are entered
* Added help text for character limit, added maxlength on input, updated snapshot

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
This looks good to me - tagging @mworrest and @blilianyu to take a look when they are back from Thanksgiving break!

https://react-app-dev.cancer.gov/drug-dictionary-app/pr-96

**Review by karlikpj — APPROVED** [review]

**Comment by blilianyu** [comment]
This looks good to me as well! @VictoriaSunNIH @mworrest

**Comment by mworrest** [comment]
Looks good, thanks!

**Review by arcepaul — APPROVED** [review]

**Comment by SupriyaSaxena0605** [comment]
looks good to me

**Pull request merged**
